/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.2.2.0 (NJsonSchema v10.1.4.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
import { __decorate, __extends, __metadata, __param, __values } from "tslib";
import 'rxjs/add/observable/fromPromise';
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import 'rxjs/add/operator/mergeMap';
import 'rxjs/add/operator/catch';
import { Observable } from 'rxjs/Observable';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
export var OM_OFFER_API_BASE_URL = new InjectionToken('OM_OFFER_API_BASE_URL');
var ServiceBaseConfig = /** @class */ (function () {
    function ServiceBaseConfig() {
    }
    return ServiceBaseConfig;
}());
export { ServiceBaseConfig };
var ServiceBase = /** @class */ (function () {
    function ServiceBase(config) {
        this.apimHeaderName = 'Ocp-Apim-Subscription-Key';
        this.tenantIdHeaderName = 'TenantId';
        this.tenantIdLocalStorageKey = 'samplicity-dtp-current-client';
        this.idTokenKey = 'samplicity-id-token';
        this.apiKey = config.key;
    }
    ServiceBase.prototype.transformOptions = function (options) {
        var headers = options.headers;
        if (this.apiKey) {
            headers = headers.append(this.apimHeaderName, this.apiKey);
        }
        var tenantId = sessionStorage.getItem(this.tenantIdLocalStorageKey);
        if (tenantId) {
            headers = headers.append(this.tenantIdHeaderName, tenantId);
        }
        var token = localStorage.getItem(this.idTokenKey);
        if (token) {
            headers = headers.append('Authorization', 'Bearer ' + token);
        }
        options.headers = headers;
        return Promise.resolve(options);
    };
    return ServiceBase;
}());
export { ServiceBase };
var OrderManagementOffer = /** @class */ (function (_super) {
    __extends(OrderManagementOffer, _super);
    function OrderManagementOffer(configuration, http, baseUrl) {
        var _this = _super.call(this, configuration) || this;
        _this.jsonParseReviver = undefined;
        _this.http = http;
        _this.baseUrl = baseUrl ? baseUrl : "";
        return _this;
    }
    /**
     * @param id (optional)
     * @param filterLinesByLiveProgramConfiguration (optional)
     * @return Success
     */
    OrderManagementOffer.prototype.getOffer = function (id, filterLinesByLiveProgramConfiguration) {
        var _this = this;
        var url_ = this.baseUrl + "/api/services/app/Offer/GetOffer?";
        if (id !== undefined)
            url_ += "id=" + encodeURIComponent("" + id) + "&";
        if (filterLinesByLiveProgramConfiguration !== undefined)
            url_ += "filterLinesByLiveProgramConfiguration=" + encodeURIComponent("" + filterLinesByLiveProgramConfiguration) + "&";
        url_ = url_.replace(/[?&]$/, "");
        var options_ = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };
        return Observable.fromPromise(this.transformOptions(options_)).flatMap(function (transformedOptions_) {
            return _this.http.request("get", url_, transformedOptions_);
        }).flatMap(function (response_) {
            return _this.processGetOffer(response_);
        }).catch(function (response_) {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return _this.processGetOffer(response_);
                }
                catch (e) {
                    return Observable.throw(e);
                }
            }
            else
                return Observable.throw(response_);
        });
    };
    OrderManagementOffer.prototype.processGetOffer = function (response) {
        var e_1, _a;
        var _this = this;
        var status = response.status;
        var responseBlob = response instanceof HttpResponse ? response.body :
            response.error instanceof Blob ? response.error : undefined;
        var _headers = {};
        if (response.headers) {
            try {
                for (var _b = __values(response.headers.keys()), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var key = _c.value;
                    _headers[key] = response.headers.get(key);
                }
            }
            catch (e_1_1) { e_1 = { error: e_1_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_1) throw e_1.error; }
            }
        }
        ;
        if (status === 200) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                var result200 = null;
                var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                result200 = AjaxResponseOfOfferDetailsDto.fromJS(resultData200);
                return Observable.of(result200);
            });
        }
        else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Observable.of(null);
    };
    /**
     * @param options (optional)
     * @return Success
     */
    OrderManagementOffer.prototype.resendSrf = function (options) {
        var _this = this;
        var url_ = this.baseUrl + "/api/services/app/Offer/ResendSrf";
        url_ = url_.replace(/[?&]$/, "");
        var content_ = JSON.stringify(options);
        var options_ = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };
        return Observable.fromPromise(this.transformOptions(options_)).flatMap(function (transformedOptions_) {
            return _this.http.request("post", url_, transformedOptions_);
        }).flatMap(function (response_) {
            return _this.processResendSrf(response_);
        }).catch(function (response_) {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return _this.processResendSrf(response_);
                }
                catch (e) {
                    return Observable.throw(e);
                }
            }
            else
                return Observable.throw(response_);
        });
    };
    OrderManagementOffer.prototype.processResendSrf = function (response) {
        var e_2, _a;
        var _this = this;
        var status = response.status;
        var responseBlob = response instanceof HttpResponse ? response.body :
            response.error instanceof Blob ? response.error : undefined;
        var _headers = {};
        if (response.headers) {
            try {
                for (var _b = __values(response.headers.keys()), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var key = _c.value;
                    _headers[key] = response.headers.get(key);
                }
            }
            catch (e_2_1) { e_2 = { error: e_2_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_2) throw e_2.error; }
            }
        }
        ;
        if (status === 200) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                var result200 = null;
                var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                result200 = AjaxResponseOfOfferDetailsDto.fromJS(resultData200);
                return Observable.of(result200);
            });
        }
        else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Observable.of(null);
    };
    /**
     * @param offerId (optional)
     * @return Success
     */
    OrderManagementOffer.prototype.viewSrf = function (offerId) {
        var _this = this;
        var url_ = this.baseUrl + "/api/services/app/Offer/ViewSrf?";
        if (offerId !== undefined)
            url_ += "offerId=" + encodeURIComponent("" + offerId) + "&";
        url_ = url_.replace(/[?&]$/, "");
        var options_ = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };
        return Observable.fromPromise(this.transformOptions(options_)).flatMap(function (transformedOptions_) {
            return _this.http.request("post", url_, transformedOptions_);
        }).flatMap(function (response_) {
            return _this.processViewSrf(response_);
        }).catch(function (response_) {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return _this.processViewSrf(response_);
                }
                catch (e) {
                    return Observable.throw(e);
                }
            }
            else
                return Observable.throw(response_);
        });
    };
    OrderManagementOffer.prototype.processViewSrf = function (response) {
        var e_3, _a;
        var _this = this;
        var status = response.status;
        var responseBlob = response instanceof HttpResponse ? response.body :
            response.error instanceof Blob ? response.error : undefined;
        var _headers = {};
        if (response.headers) {
            try {
                for (var _b = __values(response.headers.keys()), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var key = _c.value;
                    _headers[key] = response.headers.get(key);
                }
            }
            catch (e_3_1) { e_3 = { error: e_3_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_3) throw e_3.error; }
            }
        }
        ;
        if (status === 200) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                var result200 = null;
                var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                result200 = AjaxResponseOfString.fromJS(resultData200);
                return Observable.of(result200);
            });
        }
        else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Observable.of(null);
    };
    /**
     * @param offerId (optional)
     * @return Success
     */
    OrderManagementOffer.prototype.regenerateSrf = function (offerId) {
        var _this = this;
        var url_ = this.baseUrl + "/api/services/app/Offer/RegenerateSrf?";
        if (offerId !== undefined)
            url_ += "offerId=" + encodeURIComponent("" + offerId) + "&";
        url_ = url_.replace(/[?&]$/, "");
        var options_ = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };
        return Observable.fromPromise(this.transformOptions(options_)).flatMap(function (transformedOptions_) {
            return _this.http.request("post", url_, transformedOptions_);
        }).flatMap(function (response_) {
            return _this.processRegenerateSrf(response_);
        }).catch(function (response_) {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return _this.processRegenerateSrf(response_);
                }
                catch (e) {
                    return Observable.throw(e);
                }
            }
            else
                return Observable.throw(response_);
        });
    };
    OrderManagementOffer.prototype.processRegenerateSrf = function (response) {
        var e_4, _a;
        var _this = this;
        var status = response.status;
        var responseBlob = response instanceof HttpResponse ? response.body :
            response.error instanceof Blob ? response.error : undefined;
        var _headers = {};
        if (response.headers) {
            try {
                for (var _b = __values(response.headers.keys()), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var key = _c.value;
                    _headers[key] = response.headers.get(key);
                }
            }
            catch (e_4_1) { e_4 = { error: e_4_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_4) throw e_4.error; }
            }
        }
        ;
        if (status === 200) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                var result200 = null;
                var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                result200 = AjaxResponseOfOfferDetailsDto.fromJS(resultData200);
                return Observable.of(result200);
            });
        }
        else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Observable.of(null);
    };
    /**
     * @param filter (optional)
     * @return Success
     */
    OrderManagementOffer.prototype.searchOffers = function (filter) {
        var _this = this;
        var url_ = this.baseUrl + "/api/services/app/Offer/SearchOffers";
        url_ = url_.replace(/[?&]$/, "");
        var content_ = JSON.stringify(filter);
        var options_ = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };
        return Observable.fromPromise(this.transformOptions(options_)).flatMap(function (transformedOptions_) {
            return _this.http.request("post", url_, transformedOptions_);
        }).flatMap(function (response_) {
            return _this.processSearchOffers(response_);
        }).catch(function (response_) {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return _this.processSearchOffers(response_);
                }
                catch (e) {
                    return Observable.throw(e);
                }
            }
            else
                return Observable.throw(response_);
        });
    };
    OrderManagementOffer.prototype.processSearchOffers = function (response) {
        var e_5, _a;
        var _this = this;
        var status = response.status;
        var responseBlob = response instanceof HttpResponse ? response.body :
            response.error instanceof Blob ? response.error : undefined;
        var _headers = {};
        if (response.headers) {
            try {
                for (var _b = __values(response.headers.keys()), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var key = _c.value;
                    _headers[key] = response.headers.get(key);
                }
            }
            catch (e_5_1) { e_5 = { error: e_5_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_5) throw e_5.error; }
            }
        }
        ;
        if (status === 200) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                var result200 = null;
                var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                result200 = AjaxResponseOfPagedResultOfOfferSearchDto.fromJS(resultData200);
                return Observable.of(result200);
            });
        }
        else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Observable.of(null);
    };
    /**
     * @param filter (optional)
     * @return Success
     */
    OrderManagementOffer.prototype.searchOfferByFormId = function (filter) {
        var _this = this;
        var url_ = this.baseUrl + "/api/services/app/Offer/SearchOfferByFormId";
        url_ = url_.replace(/[?&]$/, "");
        var content_ = JSON.stringify(filter);
        var options_ = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };
        return Observable.fromPromise(this.transformOptions(options_)).flatMap(function (transformedOptions_) {
            return _this.http.request("post", url_, transformedOptions_);
        }).flatMap(function (response_) {
            return _this.processSearchOfferByFormId(response_);
        }).catch(function (response_) {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return _this.processSearchOfferByFormId(response_);
                }
                catch (e) {
                    return Observable.throw(e);
                }
            }
            else
                return Observable.throw(response_);
        });
    };
    OrderManagementOffer.prototype.processSearchOfferByFormId = function (response) {
        var e_6, _a;
        var _this = this;
        var status = response.status;
        var responseBlob = response instanceof HttpResponse ? response.body :
            response.error instanceof Blob ? response.error : undefined;
        var _headers = {};
        if (response.headers) {
            try {
                for (var _b = __values(response.headers.keys()), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var key = _c.value;
                    _headers[key] = response.headers.get(key);
                }
            }
            catch (e_6_1) { e_6 = { error: e_6_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_6) throw e_6.error; }
            }
        }
        ;
        if (status === 200) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                var result200 = null;
                var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                result200 = AjaxResponseOfListOfSearchOfferByFormIdResultDto.fromJS(resultData200);
                return Observable.of(result200);
            });
        }
        else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Observable.of(null);
    };
    /**
     * @param programId (optional)
     * @return Success
     */
    OrderManagementOffer.prototype.generateOfferDataFromTarget = function (programId) {
        var _this = this;
        var url_ = this.baseUrl + "/api/services/app/Offer/GenerateOfferDataFromTarget?";
        if (programId !== undefined)
            url_ += "programId=" + encodeURIComponent("" + programId) + "&";
        url_ = url_.replace(/[?&]$/, "");
        var options_ = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };
        return Observable.fromPromise(this.transformOptions(options_)).flatMap(function (transformedOptions_) {
            return _this.http.request("post", url_, transformedOptions_);
        }).flatMap(function (response_) {
            return _this.processGenerateOfferDataFromTarget(response_);
        }).catch(function (response_) {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return _this.processGenerateOfferDataFromTarget(response_);
                }
                catch (e) {
                    return Observable.throw(e);
                }
            }
            else
                return Observable.throw(response_);
        });
    };
    OrderManagementOffer.prototype.processGenerateOfferDataFromTarget = function (response) {
        var e_7, _a;
        var _this = this;
        var status = response.status;
        var responseBlob = response instanceof HttpResponse ? response.body :
            response.error instanceof Blob ? response.error : undefined;
        var _headers = {};
        if (response.headers) {
            try {
                for (var _b = __values(response.headers.keys()), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var key = _c.value;
                    _headers[key] = response.headers.get(key);
                }
            }
            catch (e_7_1) { e_7 = { error: e_7_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_7) throw e_7.error; }
            }
        }
        ;
        if (status === 200) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                var result200 = null;
                var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                result200 = AjaxResponseOfGenerateOfferResultDto.fromJS(resultData200);
                return Observable.of(result200);
            });
        }
        else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Observable.of(null);
    };
    /**
     * @param dto (optional)
     * @return Success
     */
    OrderManagementOffer.prototype.uploadOfferFile = function (dto) {
        var _this = this;
        var url_ = this.baseUrl + "/api/services/app/Offer/UploadOfferFile";
        url_ = url_.replace(/[?&]$/, "");
        var content_ = JSON.stringify(dto);
        var options_ = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };
        return Observable.fromPromise(this.transformOptions(options_)).flatMap(function (transformedOptions_) {
            return _this.http.request("post", url_, transformedOptions_);
        }).flatMap(function (response_) {
            return _this.processUploadOfferFile(response_);
        }).catch(function (response_) {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return _this.processUploadOfferFile(response_);
                }
                catch (e) {
                    return Observable.throw(e);
                }
            }
            else
                return Observable.throw(response_);
        });
    };
    OrderManagementOffer.prototype.processUploadOfferFile = function (response) {
        var e_8, _a;
        var _this = this;
        var status = response.status;
        var responseBlob = response instanceof HttpResponse ? response.body :
            response.error instanceof Blob ? response.error : undefined;
        var _headers = {};
        if (response.headers) {
            try {
                for (var _b = __values(response.headers.keys()), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var key = _c.value;
                    _headers[key] = response.headers.get(key);
                }
            }
            catch (e_8_1) { e_8 = { error: e_8_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_8) throw e_8.error; }
            }
        }
        ;
        if (status === 200) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                var result200 = null;
                var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                result200 = AjaxResponseOfOfferFileUploadDto.fromJS(resultData200);
                return Observable.of(result200);
            });
        }
        else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).flatMap(function (_responseText) {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Observable.of(null);
    };
    OrderManagementOffer = __decorate([
        Injectable(),
        __param(0, Inject(ServiceBaseConfig)), __param(1, Inject(HttpClient)), __param(2, Optional()), __param(2, Inject(OM_OFFER_API_BASE_URL)),
        __metadata("design:paramtypes", [ServiceBaseConfig, HttpClient, String])
    ], OrderManagementOffer);
    return OrderManagementOffer;
}(ServiceBase));
export { OrderManagementOffer };
var AjaxResponseOfOfferDetailsDto = /** @class */ (function () {
    function AjaxResponseOfOfferDetailsDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    AjaxResponseOfOfferDetailsDto.prototype.init = function (_data) {
        if (_data) {
            this.result = _data["result"] ? OfferDetailsDto.fromJS(_data["result"]) : undefined;
            this.targetUrl = _data["targetUrl"];
            this.success = _data["success"];
            this.error = _data["error"] ? ErrorInfo.fromJS(_data["error"]) : undefined;
            this.unAuthorizedRequest = _data["unAuthorizedRequest"];
            this.__abp = _data["__abp"];
        }
    };
    AjaxResponseOfOfferDetailsDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new AjaxResponseOfOfferDetailsDto();
        result.init(data);
        return result;
    };
    AjaxResponseOfOfferDetailsDto.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["result"] = this.result ? this.result.toJSON() : undefined;
        data["targetUrl"] = this.targetUrl;
        data["success"] = this.success;
        data["error"] = this.error ? this.error.toJSON() : undefined;
        data["unAuthorizedRequest"] = this.unAuthorizedRequest;
        data["__abp"] = this.__abp;
        return data;
    };
    AjaxResponseOfOfferDetailsDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new AjaxResponseOfOfferDetailsDto();
        result.init(json);
        return result;
    };
    return AjaxResponseOfOfferDetailsDto;
}());
export { AjaxResponseOfOfferDetailsDto };
var OfferDetailsDto = /** @class */ (function () {
    function OfferDetailsDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    OfferDetailsDto.prototype.init = function (_data) {
        var e_9, _a, e_10, _b, e_11, _c, e_12, _d, e_13, _e;
        if (_data) {
            this.id = _data["id"];
            this.requestDate = _data["requestDate"] ? new Date(_data["requestDate"].toString()) : undefined;
            this.offerId = _data["offerId"];
            this.parentOffer = _data["parentOffer"] ? SimpleOfferDto.fromJS(_data["parentOffer"]) : undefined;
            if (Array.isArray(_data["childOffers"])) {
                this.childOffers = [];
                try {
                    for (var _f = __values(_data["childOffers"]), _g = _f.next(); !_g.done; _g = _f.next()) {
                        var item = _g.value;
                        this.childOffers.push(SimpleOfferDto.fromJS(item));
                    }
                }
                catch (e_9_1) { e_9 = { error: e_9_1 }; }
                finally {
                    try {
                        if (_g && !_g.done && (_a = _f.return)) _a.call(_f);
                    }
                    finally { if (e_9) throw e_9.error; }
                }
            }
            this.formId = _data["formId"];
            this.externalOfferId = _data["externalOfferId"];
            this.resendInitiated = _data["resendInitiated"];
            this.srfSentDate = _data["srfSentDate"];
            this.offerStatusClassificationValueId = _data["offerStatusClassificationValueId"];
            this.programStatusId = _data["programStatusId"];
            this.isOfferStatusError = _data["isOfferStatusError"];
            this.isViewSrfAvailable = _data["isViewSrfAvailable"];
            this.isRegenerateSrfAvailable = _data["isRegenerateSrfAvailable"];
            this.institutionFlag = _data["institutionFlag"];
            this.repDrivenFlag = _data["repDrivenFlag"];
            if (Array.isArray(_data["offerLifeCycle"])) {
                this.offerLifeCycle = [];
                try {
                    for (var _h = __values(_data["offerLifeCycle"]), _j = _h.next(); !_j.done; _j = _h.next()) {
                        var item = _j.value;
                        this.offerLifeCycle.push(StepperLifeCycleStageDto.fromJS(item));
                    }
                }
                catch (e_10_1) { e_10 = { error: e_10_1 }; }
                finally {
                    try {
                        if (_j && !_j.done && (_b = _h.return)) _b.call(_h);
                    }
                    finally { if (e_10) throw e_10.error; }
                }
            }
            if (Array.isArray(_data["offerLines"])) {
                this.offerLines = [];
                try {
                    for (var _k = __values(_data["offerLines"]), _l = _k.next(); !_l.done; _l = _k.next()) {
                        var item = _l.value;
                        this.offerLines.push(OfferLineDto.fromJS(item));
                    }
                }
                catch (e_11_1) { e_11 = { error: e_11_1 }; }
                finally {
                    try {
                        if (_l && !_l.done && (_c = _k.return)) _c.call(_k);
                    }
                    finally { if (e_11) throw e_11.error; }
                }
            }
            this.requestorHcpId = _data["requestorHcpId"];
            this.requestorKnipperHcpId = _data["requestorKnipperHcpId"];
            this.requestorCompanyName = _data["requestorCompanyName"];
            this.requestorName = _data["requestorName"];
            this.requestorFirstName = _data["requestorFirstName"];
            this.requestorMiddleName = _data["requestorMiddleName"];
            this.requestorLastName = _data["requestorLastName"];
            this.requestorSuffixId = _data["requestorSuffixId"];
            this.requestorProfessionalDesignationId = _data["requestorProfessionalDesignationId"];
            this.requestorSpecialtyClassificationValueId = _data["requestorSpecialtyClassificationValueId"];
            this.requestorStateLicenseNbr = _data["requestorStateLicenseNbr"];
            this.requestorStateLicenseStateCode = _data["requestorStateLicenseStateCode"];
            this.requestorDEANbr = _data["requestorDEANbr"];
            this.requestorSAN = _data["requestorSAN"];
            this.requestorAddress1Text = _data["requestorAddress1Text"];
            this.requestorAddress2Text = _data["requestorAddress2Text"];
            this.requestorAddress3Text = _data["requestorAddress3Text"];
            this.requestorAddress4Text = _data["requestorAddress4Text"];
            this.requestorCityName = _data["requestorCityName"];
            this.requestorZipCode = _data["requestorZipCode"];
            this.requestorStateCode = _data["requestorStateCode"];
            this.requestorEmailAddressText = _data["requestorEmailAddressText"];
            this.requestorPhoneNbr = _data["requestorPhoneNbr"];
            this.requestorPhoneExtensionNbr = _data["requestorPhoneExtensionNbr"];
            this.requestorFaxNbr = _data["requestorFaxNbr"];
            this.recipientHcpId = _data["recipientHcpId"];
            this.recipientKnipperHcpId = _data["recipientKnipperHcpId"];
            this.recipientCompanyName = _data["recipientCompanyName"];
            this.recipientName = _data["recipientName"];
            this.recipientFirstName = _data["recipientFirstName"];
            this.recipientMiddleName = _data["recipientMiddleName"];
            this.recipientLastName = _data["recipientLastName"];
            this.recipientSuffixId = _data["recipientSuffixId"];
            this.recipientProfessionalDesignationId = _data["recipientProfessionalDesignationId"];
            this.recipientSpecialtyClassificationValueId = _data["recipientSpecialtyClassificationValueId"];
            this.recipientStateLicenseNbr = _data["recipientStateLicenseNbr"];
            this.recipientStateLicenseStateCode = _data["recipientStateLicenseStateCode"];
            this.recipientDEANbr = _data["recipientDEANbr"];
            this.recipientSAN = _data["recipientSAN"];
            this.recipientAddress1Text = _data["recipientAddress1Text"];
            this.recipientAddress2Text = _data["recipientAddress2Text"];
            this.recipientAddress3Text = _data["recipientAddress3Text"];
            this.recipientAddress4Text = _data["recipientAddress4Text"];
            this.recipientCityName = _data["recipientCityName"];
            this.recipientZipCode = _data["recipientZipCode"];
            this.recipientStateCode = _data["recipientStateCode"];
            this.recipientEmailAddressText = _data["recipientEmailAddressText"];
            this.recipientPhoneNbr = _data["recipientPhoneNbr"];
            this.recipientPhoneExtensionNbr = _data["recipientPhoneExtensionNbr"];
            this.recipientFaxNbr = _data["recipientFaxNbr"];
            this.salesRepName = _data["salesRepName"];
            this.salesRepFirstName = _data["salesRepFirstName"];
            this.salesRepLastName = _data["salesRepLastName"];
            this.salesRepEmailAddressText = _data["salesRepEmailAddressText"];
            this.salesRepNbr = _data["salesRepNbr"];
            this.territoryCode = _data["territoryCode"];
            if (Array.isArray(_data["offerHistory"])) {
                this.offerHistory = [];
                try {
                    for (var _m = __values(_data["offerHistory"]), _o = _m.next(); !_o.done; _o = _m.next()) {
                        var item = _o.value;
                        this.offerHistory.push(OfferHistoryDto.fromJS(item));
                    }
                }
                catch (e_12_1) { e_12 = { error: e_12_1 }; }
                finally {
                    try {
                        if (_o && !_o.done && (_d = _m.return)) _d.call(_m);
                    }
                    finally { if (e_12) throw e_12.error; }
                }
            }
            if (Array.isArray(_data["names"])) {
                this.names = [];
                try {
                    for (var _p = __values(_data["names"]), _q = _p.next(); !_q.done; _q = _p.next()) {
                        var item = _q.value;
                        this.names.push(LocalizedValue.fromJS(item));
                    }
                }
                catch (e_13_1) { e_13 = { error: e_13_1 }; }
                finally {
                    try {
                        if (_q && !_q.done && (_e = _p.return)) _e.call(_p);
                    }
                    finally { if (e_13) throw e_13.error; }
                }
            }
        }
    };
    OfferDetailsDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new OfferDetailsDto();
        result.init(data);
        return result;
    };
    OfferDetailsDto.prototype.toJSON = function (data) {
        var e_14, _a, e_15, _b, e_16, _c, e_17, _d, e_18, _e;
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["requestDate"] = this.requestDate ? this.requestDate.toISOString() : undefined;
        data["offerId"] = this.offerId;
        data["parentOffer"] = this.parentOffer ? this.parentOffer.toJSON() : undefined;
        if (Array.isArray(this.childOffers)) {
            data["childOffers"] = [];
            try {
                for (var _f = __values(this.childOffers), _g = _f.next(); !_g.done; _g = _f.next()) {
                    var item = _g.value;
                    data["childOffers"].push(item.toJSON());
                }
            }
            catch (e_14_1) { e_14 = { error: e_14_1 }; }
            finally {
                try {
                    if (_g && !_g.done && (_a = _f.return)) _a.call(_f);
                }
                finally { if (e_14) throw e_14.error; }
            }
        }
        data["formId"] = this.formId;
        data["externalOfferId"] = this.externalOfferId;
        data["resendInitiated"] = this.resendInitiated;
        data["srfSentDate"] = this.srfSentDate;
        data["offerStatusClassificationValueId"] = this.offerStatusClassificationValueId;
        data["programStatusId"] = this.programStatusId;
        data["isOfferStatusError"] = this.isOfferStatusError;
        data["isViewSrfAvailable"] = this.isViewSrfAvailable;
        data["isRegenerateSrfAvailable"] = this.isRegenerateSrfAvailable;
        data["institutionFlag"] = this.institutionFlag;
        data["repDrivenFlag"] = this.repDrivenFlag;
        if (Array.isArray(this.offerLifeCycle)) {
            data["offerLifeCycle"] = [];
            try {
                for (var _h = __values(this.offerLifeCycle), _j = _h.next(); !_j.done; _j = _h.next()) {
                    var item = _j.value;
                    data["offerLifeCycle"].push(item.toJSON());
                }
            }
            catch (e_15_1) { e_15 = { error: e_15_1 }; }
            finally {
                try {
                    if (_j && !_j.done && (_b = _h.return)) _b.call(_h);
                }
                finally { if (e_15) throw e_15.error; }
            }
        }
        if (Array.isArray(this.offerLines)) {
            data["offerLines"] = [];
            try {
                for (var _k = __values(this.offerLines), _l = _k.next(); !_l.done; _l = _k.next()) {
                    var item = _l.value;
                    data["offerLines"].push(item.toJSON());
                }
            }
            catch (e_16_1) { e_16 = { error: e_16_1 }; }
            finally {
                try {
                    if (_l && !_l.done && (_c = _k.return)) _c.call(_k);
                }
                finally { if (e_16) throw e_16.error; }
            }
        }
        data["requestorHcpId"] = this.requestorHcpId;
        data["requestorKnipperHcpId"] = this.requestorKnipperHcpId;
        data["requestorCompanyName"] = this.requestorCompanyName;
        data["requestorName"] = this.requestorName;
        data["requestorFirstName"] = this.requestorFirstName;
        data["requestorMiddleName"] = this.requestorMiddleName;
        data["requestorLastName"] = this.requestorLastName;
        data["requestorSuffixId"] = this.requestorSuffixId;
        data["requestorProfessionalDesignationId"] = this.requestorProfessionalDesignationId;
        data["requestorSpecialtyClassificationValueId"] = this.requestorSpecialtyClassificationValueId;
        data["requestorStateLicenseNbr"] = this.requestorStateLicenseNbr;
        data["requestorStateLicenseStateCode"] = this.requestorStateLicenseStateCode;
        data["requestorDEANbr"] = this.requestorDEANbr;
        data["requestorSAN"] = this.requestorSAN;
        data["requestorAddress1Text"] = this.requestorAddress1Text;
        data["requestorAddress2Text"] = this.requestorAddress2Text;
        data["requestorAddress3Text"] = this.requestorAddress3Text;
        data["requestorAddress4Text"] = this.requestorAddress4Text;
        data["requestorCityName"] = this.requestorCityName;
        data["requestorZipCode"] = this.requestorZipCode;
        data["requestorStateCode"] = this.requestorStateCode;
        data["requestorEmailAddressText"] = this.requestorEmailAddressText;
        data["requestorPhoneNbr"] = this.requestorPhoneNbr;
        data["requestorPhoneExtensionNbr"] = this.requestorPhoneExtensionNbr;
        data["requestorFaxNbr"] = this.requestorFaxNbr;
        data["recipientHcpId"] = this.recipientHcpId;
        data["recipientKnipperHcpId"] = this.recipientKnipperHcpId;
        data["recipientCompanyName"] = this.recipientCompanyName;
        data["recipientName"] = this.recipientName;
        data["recipientFirstName"] = this.recipientFirstName;
        data["recipientMiddleName"] = this.recipientMiddleName;
        data["recipientLastName"] = this.recipientLastName;
        data["recipientSuffixId"] = this.recipientSuffixId;
        data["recipientProfessionalDesignationId"] = this.recipientProfessionalDesignationId;
        data["recipientSpecialtyClassificationValueId"] = this.recipientSpecialtyClassificationValueId;
        data["recipientStateLicenseNbr"] = this.recipientStateLicenseNbr;
        data["recipientStateLicenseStateCode"] = this.recipientStateLicenseStateCode;
        data["recipientDEANbr"] = this.recipientDEANbr;
        data["recipientSAN"] = this.recipientSAN;
        data["recipientAddress1Text"] = this.recipientAddress1Text;
        data["recipientAddress2Text"] = this.recipientAddress2Text;
        data["recipientAddress3Text"] = this.recipientAddress3Text;
        data["recipientAddress4Text"] = this.recipientAddress4Text;
        data["recipientCityName"] = this.recipientCityName;
        data["recipientZipCode"] = this.recipientZipCode;
        data["recipientStateCode"] = this.recipientStateCode;
        data["recipientEmailAddressText"] = this.recipientEmailAddressText;
        data["recipientPhoneNbr"] = this.recipientPhoneNbr;
        data["recipientPhoneExtensionNbr"] = this.recipientPhoneExtensionNbr;
        data["recipientFaxNbr"] = this.recipientFaxNbr;
        data["salesRepName"] = this.salesRepName;
        data["salesRepFirstName"] = this.salesRepFirstName;
        data["salesRepLastName"] = this.salesRepLastName;
        data["salesRepEmailAddressText"] = this.salesRepEmailAddressText;
        data["salesRepNbr"] = this.salesRepNbr;
        data["territoryCode"] = this.territoryCode;
        if (Array.isArray(this.offerHistory)) {
            data["offerHistory"] = [];
            try {
                for (var _m = __values(this.offerHistory), _o = _m.next(); !_o.done; _o = _m.next()) {
                    var item = _o.value;
                    data["offerHistory"].push(item.toJSON());
                }
            }
            catch (e_17_1) { e_17 = { error: e_17_1 }; }
            finally {
                try {
                    if (_o && !_o.done && (_d = _m.return)) _d.call(_m);
                }
                finally { if (e_17) throw e_17.error; }
            }
        }
        if (Array.isArray(this.names)) {
            data["names"] = [];
            try {
                for (var _p = __values(this.names), _q = _p.next(); !_q.done; _q = _p.next()) {
                    var item = _q.value;
                    data["names"].push(item.toJSON());
                }
            }
            catch (e_18_1) { e_18 = { error: e_18_1 }; }
            finally {
                try {
                    if (_q && !_q.done && (_e = _p.return)) _e.call(_p);
                }
                finally { if (e_18) throw e_18.error; }
            }
        }
        return data;
    };
    OfferDetailsDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new OfferDetailsDto();
        result.init(json);
        return result;
    };
    return OfferDetailsDto;
}());
export { OfferDetailsDto };
var ErrorInfo = /** @class */ (function () {
    function ErrorInfo(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    ErrorInfo.prototype.init = function (_data) {
        var e_19, _a;
        if (_data) {
            this.code = _data["code"];
            this.message = _data["message"];
            this.details = _data["details"];
            if (Array.isArray(_data["validationErrors"])) {
                this.validationErrors = [];
                try {
                    for (var _b = __values(_data["validationErrors"]), _c = _b.next(); !_c.done; _c = _b.next()) {
                        var item = _c.value;
                        this.validationErrors.push(ValidationErrorInfo.fromJS(item));
                    }
                }
                catch (e_19_1) { e_19 = { error: e_19_1 }; }
                finally {
                    try {
                        if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                    }
                    finally { if (e_19) throw e_19.error; }
                }
            }
        }
    };
    ErrorInfo.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new ErrorInfo();
        result.init(data);
        return result;
    };
    ErrorInfo.prototype.toJSON = function (data) {
        var e_20, _a;
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        data["message"] = this.message;
        data["details"] = this.details;
        if (Array.isArray(this.validationErrors)) {
            data["validationErrors"] = [];
            try {
                for (var _b = __values(this.validationErrors), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var item = _c.value;
                    data["validationErrors"].push(item.toJSON());
                }
            }
            catch (e_20_1) { e_20 = { error: e_20_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_20) throw e_20.error; }
            }
        }
        return data;
    };
    ErrorInfo.prototype.clone = function () {
        var json = this.toJSON();
        var result = new ErrorInfo();
        result.init(json);
        return result;
    };
    return ErrorInfo;
}());
export { ErrorInfo };
var SimpleOfferDto = /** @class */ (function () {
    function SimpleOfferDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    SimpleOfferDto.prototype.init = function (_data) {
        if (_data) {
            this.id = _data["id"];
            this.offerId = _data["offerId"];
        }
    };
    SimpleOfferDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new SimpleOfferDto();
        result.init(data);
        return result;
    };
    SimpleOfferDto.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["offerId"] = this.offerId;
        return data;
    };
    SimpleOfferDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new SimpleOfferDto();
        result.init(json);
        return result;
    };
    return SimpleOfferDto;
}());
export { SimpleOfferDto };
var StepperLifeCycleStageDto = /** @class */ (function () {
    function StepperLifeCycleStageDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    StepperLifeCycleStageDto.prototype.init = function (_data) {
        if (_data) {
            this.classificationValueId = _data["classificationValueId"];
            this.index = _data["index"];
            this.status = _data["status"];
        }
    };
    StepperLifeCycleStageDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new StepperLifeCycleStageDto();
        result.init(data);
        return result;
    };
    StepperLifeCycleStageDto.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["classificationValueId"] = this.classificationValueId;
        data["index"] = this.index;
        data["status"] = this.status;
        return data;
    };
    StepperLifeCycleStageDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new StepperLifeCycleStageDto();
        result.init(json);
        return result;
    };
    return StepperLifeCycleStageDto;
}());
export { StepperLifeCycleStageDto };
var OfferLineDto = /** @class */ (function () {
    function OfferLineDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    OfferLineDto.prototype.init = function (_data) {
        var e_21, _a;
        if (_data) {
            this.id = _data["id"];
            this.productId = _data["productId"];
            this.wmsProductId = _data["wmsProductId"];
            this.wmsProductName = _data["wmsProductName"];
            this.offeredQty = _data["offeredQty"];
            this.distributionUoMClassificationValueId = _data["distributionUoMClassificationValueId"];
            this.displayQuantity = _data["displayQuantity"];
            if (Array.isArray(_data["names"])) {
                this.names = [];
                try {
                    for (var _b = __values(_data["names"]), _c = _b.next(); !_c.done; _c = _b.next()) {
                        var item = _c.value;
                        this.names.push(LocalizedValue.fromJS(item));
                    }
                }
                catch (e_21_1) { e_21 = { error: e_21_1 }; }
                finally {
                    try {
                        if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                    }
                    finally { if (e_21) throw e_21.error; }
                }
            }
        }
    };
    OfferLineDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new OfferLineDto();
        result.init(data);
        return result;
    };
    OfferLineDto.prototype.toJSON = function (data) {
        var e_22, _a;
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["productId"] = this.productId;
        data["wmsProductId"] = this.wmsProductId;
        data["wmsProductName"] = this.wmsProductName;
        data["offeredQty"] = this.offeredQty;
        data["distributionUoMClassificationValueId"] = this.distributionUoMClassificationValueId;
        data["displayQuantity"] = this.displayQuantity;
        if (Array.isArray(this.names)) {
            data["names"] = [];
            try {
                for (var _b = __values(this.names), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var item = _c.value;
                    data["names"].push(item.toJSON());
                }
            }
            catch (e_22_1) { e_22 = { error: e_22_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_22) throw e_22.error; }
            }
        }
        return data;
    };
    OfferLineDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new OfferLineDto();
        result.init(json);
        return result;
    };
    return OfferLineDto;
}());
export { OfferLineDto };
var OfferHistoryDto = /** @class */ (function () {
    function OfferHistoryDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    OfferHistoryDto.prototype.init = function (_data) {
        var e_23, _a;
        if (_data) {
            this.id = _data["id"];
            this.isOfferStatusError = _data["isOfferStatusError"];
            this.offerStatusClassificationValueId = _data["offerStatusClassificationValueId"];
            this.activityTypeClassificationValueId = _data["activityTypeClassificationValueId"];
            this.contactMethodDescription = _data["contactMethodDescription"];
            this.creationTime = _data["creationTime"] ? new Date(_data["creationTime"].toString()) : undefined;
            if (Array.isArray(_data["names"])) {
                this.names = [];
                try {
                    for (var _b = __values(_data["names"]), _c = _b.next(); !_c.done; _c = _b.next()) {
                        var item = _c.value;
                        this.names.push(LocalizedValue.fromJS(item));
                    }
                }
                catch (e_23_1) { e_23 = { error: e_23_1 }; }
                finally {
                    try {
                        if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                    }
                    finally { if (e_23) throw e_23.error; }
                }
            }
        }
    };
    OfferHistoryDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new OfferHistoryDto();
        result.init(data);
        return result;
    };
    OfferHistoryDto.prototype.toJSON = function (data) {
        var e_24, _a;
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["isOfferStatusError"] = this.isOfferStatusError;
        data["offerStatusClassificationValueId"] = this.offerStatusClassificationValueId;
        data["activityTypeClassificationValueId"] = this.activityTypeClassificationValueId;
        data["contactMethodDescription"] = this.contactMethodDescription;
        data["creationTime"] = this.creationTime ? this.creationTime.toISOString() : undefined;
        if (Array.isArray(this.names)) {
            data["names"] = [];
            try {
                for (var _b = __values(this.names), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var item = _c.value;
                    data["names"].push(item.toJSON());
                }
            }
            catch (e_24_1) { e_24 = { error: e_24_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_24) throw e_24.error; }
            }
        }
        return data;
    };
    OfferHistoryDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new OfferHistoryDto();
        result.init(json);
        return result;
    };
    return OfferHistoryDto;
}());
export { OfferHistoryDto };
var LocalizedValue = /** @class */ (function () {
    function LocalizedValue(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    LocalizedValue.prototype.init = function (_data) {
        if (_data) {
            this.language = _data["language"];
            this.value = _data["value"];
        }
    };
    LocalizedValue.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new LocalizedValue();
        result.init(data);
        return result;
    };
    LocalizedValue.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["language"] = this.language;
        data["value"] = this.value;
        return data;
    };
    LocalizedValue.prototype.clone = function () {
        var json = this.toJSON();
        var result = new LocalizedValue();
        result.init(json);
        return result;
    };
    return LocalizedValue;
}());
export { LocalizedValue };
var ValidationErrorInfo = /** @class */ (function () {
    function ValidationErrorInfo(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    ValidationErrorInfo.prototype.init = function (_data) {
        var e_25, _a;
        if (_data) {
            this.message = _data["message"];
            if (Array.isArray(_data["members"])) {
                this.members = [];
                try {
                    for (var _b = __values(_data["members"]), _c = _b.next(); !_c.done; _c = _b.next()) {
                        var item = _c.value;
                        this.members.push(item);
                    }
                }
                catch (e_25_1) { e_25 = { error: e_25_1 }; }
                finally {
                    try {
                        if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                    }
                    finally { if (e_25) throw e_25.error; }
                }
            }
        }
    };
    ValidationErrorInfo.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new ValidationErrorInfo();
        result.init(data);
        return result;
    };
    ValidationErrorInfo.prototype.toJSON = function (data) {
        var e_26, _a;
        data = typeof data === 'object' ? data : {};
        data["message"] = this.message;
        if (Array.isArray(this.members)) {
            data["members"] = [];
            try {
                for (var _b = __values(this.members), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var item = _c.value;
                    data["members"].push(item);
                }
            }
            catch (e_26_1) { e_26 = { error: e_26_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_26) throw e_26.error; }
            }
        }
        return data;
    };
    ValidationErrorInfo.prototype.clone = function () {
        var json = this.toJSON();
        var result = new ValidationErrorInfo();
        result.init(json);
        return result;
    };
    return ValidationErrorInfo;
}());
export { ValidationErrorInfo };
var OfferResendSrfOptionsDto = /** @class */ (function () {
    function OfferResendSrfOptionsDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    OfferResendSrfOptionsDto.prototype.init = function (_data) {
        if (_data) {
            this.contactMethodTypeId = _data["contactMethodTypeId"];
            this.contactMethodDescription = _data["contactMethodDescription"];
            this.id = _data["id"];
        }
    };
    OfferResendSrfOptionsDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new OfferResendSrfOptionsDto();
        result.init(data);
        return result;
    };
    OfferResendSrfOptionsDto.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["contactMethodTypeId"] = this.contactMethodTypeId;
        data["contactMethodDescription"] = this.contactMethodDescription;
        data["id"] = this.id;
        return data;
    };
    OfferResendSrfOptionsDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new OfferResendSrfOptionsDto();
        result.init(json);
        return result;
    };
    return OfferResendSrfOptionsDto;
}());
export { OfferResendSrfOptionsDto };
var AjaxResponseOfString = /** @class */ (function () {
    function AjaxResponseOfString(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    AjaxResponseOfString.prototype.init = function (_data) {
        if (_data) {
            this.result = _data["result"];
            this.targetUrl = _data["targetUrl"];
            this.success = _data["success"];
            this.error = _data["error"] ? ErrorInfo.fromJS(_data["error"]) : undefined;
            this.unAuthorizedRequest = _data["unAuthorizedRequest"];
            this.__abp = _data["__abp"];
        }
    };
    AjaxResponseOfString.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new AjaxResponseOfString();
        result.init(data);
        return result;
    };
    AjaxResponseOfString.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["result"] = this.result;
        data["targetUrl"] = this.targetUrl;
        data["success"] = this.success;
        data["error"] = this.error ? this.error.toJSON() : undefined;
        data["unAuthorizedRequest"] = this.unAuthorizedRequest;
        data["__abp"] = this.__abp;
        return data;
    };
    AjaxResponseOfString.prototype.clone = function () {
        var json = this.toJSON();
        var result = new AjaxResponseOfString();
        result.init(json);
        return result;
    };
    return AjaxResponseOfString;
}());
export { AjaxResponseOfString };
var OfferSearchFilterDto = /** @class */ (function () {
    function OfferSearchFilterDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    OfferSearchFilterDto.prototype.init = function (_data) {
        var e_27, _a, e_28, _b;
        if (_data) {
            this.programId = _data["programId"];
            this.offerId = _data["offerId"];
            this.externalOfferId = _data["externalOfferId"];
            this.formId = _data["formId"];
            if (Array.isArray(_data["offerStatusClassificationValueIds"])) {
                this.offerStatusClassificationValueIds = [];
                try {
                    for (var _c = __values(_data["offerStatusClassificationValueIds"]), _d = _c.next(); !_d.done; _d = _c.next()) {
                        var item = _d.value;
                        this.offerStatusClassificationValueIds.push(item);
                    }
                }
                catch (e_27_1) { e_27 = { error: e_27_1 }; }
                finally {
                    try {
                        if (_d && !_d.done && (_a = _c.return)) _a.call(_c);
                    }
                    finally { if (e_27) throw e_27.error; }
                }
            }
            if (Array.isArray(_data["srfGenerationSourceIds"])) {
                this.srfGenerationSourceIds = [];
                try {
                    for (var _e = __values(_data["srfGenerationSourceIds"]), _f = _e.next(); !_f.done; _f = _e.next()) {
                        var item = _f.value;
                        this.srfGenerationSourceIds.push(item);
                    }
                }
                catch (e_28_1) { e_28 = { error: e_28_1 }; }
                finally {
                    try {
                        if (_f && !_f.done && (_b = _e.return)) _b.call(_e);
                    }
                    finally { if (e_28) throw e_28.error; }
                }
            }
            this.requestorHcpLastName = _data["requestorHcpLastName"];
            this.requestorHcpFirstName = _data["requestorHcpFirstName"];
            this.requestorHcpKId = _data["requestorHcpKId"];
            this.salesRepFirstName = _data["salesRepFirstName"];
            this.salesRepLastName = _data["salesRepLastName"];
            this.salesRepId = _data["salesRepId"];
            this.recipientInstitutionName = _data["recipientInstitutionName"];
            this.pageSize = _data["pageSize"];
            this.pageNumber = _data["pageNumber"];
            this.sortBy = _data["sortBy"];
            this.filterString = _data["filterString"];
        }
    };
    OfferSearchFilterDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new OfferSearchFilterDto();
        result.init(data);
        return result;
    };
    OfferSearchFilterDto.prototype.toJSON = function (data) {
        var e_29, _a, e_30, _b;
        data = typeof data === 'object' ? data : {};
        data["programId"] = this.programId;
        data["offerId"] = this.offerId;
        data["externalOfferId"] = this.externalOfferId;
        data["formId"] = this.formId;
        if (Array.isArray(this.offerStatusClassificationValueIds)) {
            data["offerStatusClassificationValueIds"] = [];
            try {
                for (var _c = __values(this.offerStatusClassificationValueIds), _d = _c.next(); !_d.done; _d = _c.next()) {
                    var item = _d.value;
                    data["offerStatusClassificationValueIds"].push(item);
                }
            }
            catch (e_29_1) { e_29 = { error: e_29_1 }; }
            finally {
                try {
                    if (_d && !_d.done && (_a = _c.return)) _a.call(_c);
                }
                finally { if (e_29) throw e_29.error; }
            }
        }
        if (Array.isArray(this.srfGenerationSourceIds)) {
            data["srfGenerationSourceIds"] = [];
            try {
                for (var _e = __values(this.srfGenerationSourceIds), _f = _e.next(); !_f.done; _f = _e.next()) {
                    var item = _f.value;
                    data["srfGenerationSourceIds"].push(item);
                }
            }
            catch (e_30_1) { e_30 = { error: e_30_1 }; }
            finally {
                try {
                    if (_f && !_f.done && (_b = _e.return)) _b.call(_e);
                }
                finally { if (e_30) throw e_30.error; }
            }
        }
        data["requestorHcpLastName"] = this.requestorHcpLastName;
        data["requestorHcpFirstName"] = this.requestorHcpFirstName;
        data["requestorHcpKId"] = this.requestorHcpKId;
        data["salesRepFirstName"] = this.salesRepFirstName;
        data["salesRepLastName"] = this.salesRepLastName;
        data["salesRepId"] = this.salesRepId;
        data["recipientInstitutionName"] = this.recipientInstitutionName;
        data["pageSize"] = this.pageSize;
        data["pageNumber"] = this.pageNumber;
        data["sortBy"] = this.sortBy;
        data["filterString"] = this.filterString;
        return data;
    };
    OfferSearchFilterDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new OfferSearchFilterDto();
        result.init(json);
        return result;
    };
    return OfferSearchFilterDto;
}());
export { OfferSearchFilterDto };
var AjaxResponseOfPagedResultOfOfferSearchDto = /** @class */ (function () {
    function AjaxResponseOfPagedResultOfOfferSearchDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    AjaxResponseOfPagedResultOfOfferSearchDto.prototype.init = function (_data) {
        if (_data) {
            this.result = _data["result"] ? PagedResultOfOfferSearchDto.fromJS(_data["result"]) : undefined;
            this.targetUrl = _data["targetUrl"];
            this.success = _data["success"];
            this.error = _data["error"] ? ErrorInfo.fromJS(_data["error"]) : undefined;
            this.unAuthorizedRequest = _data["unAuthorizedRequest"];
            this.__abp = _data["__abp"];
        }
    };
    AjaxResponseOfPagedResultOfOfferSearchDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new AjaxResponseOfPagedResultOfOfferSearchDto();
        result.init(data);
        return result;
    };
    AjaxResponseOfPagedResultOfOfferSearchDto.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["result"] = this.result ? this.result.toJSON() : undefined;
        data["targetUrl"] = this.targetUrl;
        data["success"] = this.success;
        data["error"] = this.error ? this.error.toJSON() : undefined;
        data["unAuthorizedRequest"] = this.unAuthorizedRequest;
        data["__abp"] = this.__abp;
        return data;
    };
    AjaxResponseOfPagedResultOfOfferSearchDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new AjaxResponseOfPagedResultOfOfferSearchDto();
        result.init(json);
        return result;
    };
    return AjaxResponseOfPagedResultOfOfferSearchDto;
}());
export { AjaxResponseOfPagedResultOfOfferSearchDto };
var PagedResultOfOfferSearchDto = /** @class */ (function () {
    function PagedResultOfOfferSearchDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    PagedResultOfOfferSearchDto.prototype.init = function (_data) {
        var e_31, _a;
        if (_data) {
            this.totalCount = _data["totalCount"];
            if (Array.isArray(_data["items"])) {
                this.items = [];
                try {
                    for (var _b = __values(_data["items"]), _c = _b.next(); !_c.done; _c = _b.next()) {
                        var item = _c.value;
                        this.items.push(OfferSearchDto.fromJS(item));
                    }
                }
                catch (e_31_1) { e_31 = { error: e_31_1 }; }
                finally {
                    try {
                        if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                    }
                    finally { if (e_31) throw e_31.error; }
                }
            }
        }
    };
    PagedResultOfOfferSearchDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new PagedResultOfOfferSearchDto();
        result.init(data);
        return result;
    };
    PagedResultOfOfferSearchDto.prototype.toJSON = function (data) {
        var e_32, _a;
        data = typeof data === 'object' ? data : {};
        data["totalCount"] = this.totalCount;
        if (Array.isArray(this.items)) {
            data["items"] = [];
            try {
                for (var _b = __values(this.items), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var item = _c.value;
                    data["items"].push(item.toJSON());
                }
            }
            catch (e_32_1) { e_32 = { error: e_32_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_32) throw e_32.error; }
            }
        }
        return data;
    };
    PagedResultOfOfferSearchDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new PagedResultOfOfferSearchDto();
        result.init(json);
        return result;
    };
    return PagedResultOfOfferSearchDto;
}());
export { PagedResultOfOfferSearchDto };
var OfferSearchDto = /** @class */ (function () {
    function OfferSearchDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    OfferSearchDto.prototype.init = function (_data) {
        var e_33, _a;
        if (_data) {
            this.id = _data["id"];
            this.offerId = _data["offerId"];
            this.offerStatus = _data["offerStatus"];
            this.externalOfferId = _data["externalOfferId"];
            this.formId = _data["formId"];
            this.requestorHcpName = _data["requestorHcpName"];
            this.requestorHcpKId = _data["requestorHcpKId"];
            this.salesRepName = _data["salesRepName"];
            this.salesRepId = _data["salesRepId"];
            this.institutionName = _data["institutionName"];
            this.isOfferStatusError = _data["isOfferStatusError"];
            this.newFlag = _data["newFlag"];
            if (Array.isArray(_data["names"])) {
                this.names = [];
                try {
                    for (var _b = __values(_data["names"]), _c = _b.next(); !_c.done; _c = _b.next()) {
                        var item = _c.value;
                        this.names.push(LocalizedValue.fromJS(item));
                    }
                }
                catch (e_33_1) { e_33 = { error: e_33_1 }; }
                finally {
                    try {
                        if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                    }
                    finally { if (e_33) throw e_33.error; }
                }
            }
        }
    };
    OfferSearchDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new OfferSearchDto();
        result.init(data);
        return result;
    };
    OfferSearchDto.prototype.toJSON = function (data) {
        var e_34, _a;
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["offerId"] = this.offerId;
        data["offerStatus"] = this.offerStatus;
        data["externalOfferId"] = this.externalOfferId;
        data["formId"] = this.formId;
        data["requestorHcpName"] = this.requestorHcpName;
        data["requestorHcpKId"] = this.requestorHcpKId;
        data["salesRepName"] = this.salesRepName;
        data["salesRepId"] = this.salesRepId;
        data["institutionName"] = this.institutionName;
        data["isOfferStatusError"] = this.isOfferStatusError;
        data["newFlag"] = this.newFlag;
        if (Array.isArray(this.names)) {
            data["names"] = [];
            try {
                for (var _b = __values(this.names), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var item = _c.value;
                    data["names"].push(item.toJSON());
                }
            }
            catch (e_34_1) { e_34 = { error: e_34_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_34) throw e_34.error; }
            }
        }
        return data;
    };
    OfferSearchDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new OfferSearchDto();
        result.init(json);
        return result;
    };
    return OfferSearchDto;
}());
export { OfferSearchDto };
var OfferByFormIdSearchFilterDto = /** @class */ (function () {
    function OfferByFormIdSearchFilterDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    OfferByFormIdSearchFilterDto.prototype.init = function (_data) {
        if (_data) {
            this.formId = _data["formId"];
        }
    };
    OfferByFormIdSearchFilterDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new OfferByFormIdSearchFilterDto();
        result.init(data);
        return result;
    };
    OfferByFormIdSearchFilterDto.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["formId"] = this.formId;
        return data;
    };
    OfferByFormIdSearchFilterDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new OfferByFormIdSearchFilterDto();
        result.init(json);
        return result;
    };
    return OfferByFormIdSearchFilterDto;
}());
export { OfferByFormIdSearchFilterDto };
var AjaxResponseOfListOfSearchOfferByFormIdResultDto = /** @class */ (function () {
    function AjaxResponseOfListOfSearchOfferByFormIdResultDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    AjaxResponseOfListOfSearchOfferByFormIdResultDto.prototype.init = function (_data) {
        var e_35, _a;
        if (_data) {
            if (Array.isArray(_data["result"])) {
                this.result = [];
                try {
                    for (var _b = __values(_data["result"]), _c = _b.next(); !_c.done; _c = _b.next()) {
                        var item = _c.value;
                        this.result.push(SearchOfferByFormIdResultDto.fromJS(item));
                    }
                }
                catch (e_35_1) { e_35 = { error: e_35_1 }; }
                finally {
                    try {
                        if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                    }
                    finally { if (e_35) throw e_35.error; }
                }
            }
            this.targetUrl = _data["targetUrl"];
            this.success = _data["success"];
            this.error = _data["error"] ? ErrorInfo.fromJS(_data["error"]) : undefined;
            this.unAuthorizedRequest = _data["unAuthorizedRequest"];
            this.__abp = _data["__abp"];
        }
    };
    AjaxResponseOfListOfSearchOfferByFormIdResultDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new AjaxResponseOfListOfSearchOfferByFormIdResultDto();
        result.init(data);
        return result;
    };
    AjaxResponseOfListOfSearchOfferByFormIdResultDto.prototype.toJSON = function (data) {
        var e_36, _a;
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.result)) {
            data["result"] = [];
            try {
                for (var _b = __values(this.result), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var item = _c.value;
                    data["result"].push(item.toJSON());
                }
            }
            catch (e_36_1) { e_36 = { error: e_36_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_36) throw e_36.error; }
            }
        }
        data["targetUrl"] = this.targetUrl;
        data["success"] = this.success;
        data["error"] = this.error ? this.error.toJSON() : undefined;
        data["unAuthorizedRequest"] = this.unAuthorizedRequest;
        data["__abp"] = this.__abp;
        return data;
    };
    AjaxResponseOfListOfSearchOfferByFormIdResultDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new AjaxResponseOfListOfSearchOfferByFormIdResultDto();
        result.init(json);
        return result;
    };
    return AjaxResponseOfListOfSearchOfferByFormIdResultDto;
}());
export { AjaxResponseOfListOfSearchOfferByFormIdResultDto };
var SearchOfferByFormIdResultDto = /** @class */ (function () {
    function SearchOfferByFormIdResultDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    SearchOfferByFormIdResultDto.prototype.init = function (_data) {
        if (_data) {
            this.offerId = _data["offerId"];
            this.offerNumber = _data["offerNumber"];
            this.formId = _data["formId"];
        }
    };
    SearchOfferByFormIdResultDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new SearchOfferByFormIdResultDto();
        result.init(data);
        return result;
    };
    SearchOfferByFormIdResultDto.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["offerId"] = this.offerId;
        data["offerNumber"] = this.offerNumber;
        data["formId"] = this.formId;
        return data;
    };
    SearchOfferByFormIdResultDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new SearchOfferByFormIdResultDto();
        result.init(json);
        return result;
    };
    return SearchOfferByFormIdResultDto;
}());
export { SearchOfferByFormIdResultDto };
var AjaxResponseOfGenerateOfferResultDto = /** @class */ (function () {
    function AjaxResponseOfGenerateOfferResultDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    AjaxResponseOfGenerateOfferResultDto.prototype.init = function (_data) {
        if (_data) {
            this.result = _data["result"] ? GenerateOfferResultDto.fromJS(_data["result"]) : undefined;
            this.targetUrl = _data["targetUrl"];
            this.success = _data["success"];
            this.error = _data["error"] ? ErrorInfo.fromJS(_data["error"]) : undefined;
            this.unAuthorizedRequest = _data["unAuthorizedRequest"];
            this.__abp = _data["__abp"];
        }
    };
    AjaxResponseOfGenerateOfferResultDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new AjaxResponseOfGenerateOfferResultDto();
        result.init(data);
        return result;
    };
    AjaxResponseOfGenerateOfferResultDto.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["result"] = this.result ? this.result.toJSON() : undefined;
        data["targetUrl"] = this.targetUrl;
        data["success"] = this.success;
        data["error"] = this.error ? this.error.toJSON() : undefined;
        data["unAuthorizedRequest"] = this.unAuthorizedRequest;
        data["__abp"] = this.__abp;
        return data;
    };
    AjaxResponseOfGenerateOfferResultDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new AjaxResponseOfGenerateOfferResultDto();
        result.init(json);
        return result;
    };
    return AjaxResponseOfGenerateOfferResultDto;
}());
export { AjaxResponseOfGenerateOfferResultDto };
var GenerateOfferResultDto = /** @class */ (function () {
    function GenerateOfferResultDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    GenerateOfferResultDto.prototype.init = function (_data) {
        var e_37, _a;
        if (_data) {
            this.offerGeneratedCount = _data["offerGeneratedCount"];
            this.totalTargetRecordCount = _data["totalTargetRecordCount"];
            this.processedTargetRecordCount = _data["processedTargetRecordCount"];
            this.failedTargetRecordCount = _data["failedTargetRecordCount"];
            this.resultCode = _data["resultCode"];
            this.resultCodeStr = _data["resultCodeStr"];
            if (Array.isArray(_data["generatedOfferIds"])) {
                this.generatedOfferIds = [];
                try {
                    for (var _b = __values(_data["generatedOfferIds"]), _c = _b.next(); !_c.done; _c = _b.next()) {
                        var item = _c.value;
                        this.generatedOfferIds.push(item);
                    }
                }
                catch (e_37_1) { e_37 = { error: e_37_1 }; }
                finally {
                    try {
                        if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                    }
                    finally { if (e_37) throw e_37.error; }
                }
            }
        }
    };
    GenerateOfferResultDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new GenerateOfferResultDto();
        result.init(data);
        return result;
    };
    GenerateOfferResultDto.prototype.toJSON = function (data) {
        var e_38, _a;
        data = typeof data === 'object' ? data : {};
        data["offerGeneratedCount"] = this.offerGeneratedCount;
        data["totalTargetRecordCount"] = this.totalTargetRecordCount;
        data["processedTargetRecordCount"] = this.processedTargetRecordCount;
        data["failedTargetRecordCount"] = this.failedTargetRecordCount;
        data["resultCode"] = this.resultCode;
        data["resultCodeStr"] = this.resultCodeStr;
        if (Array.isArray(this.generatedOfferIds)) {
            data["generatedOfferIds"] = [];
            try {
                for (var _b = __values(this.generatedOfferIds), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var item = _c.value;
                    data["generatedOfferIds"].push(item);
                }
            }
            catch (e_38_1) { e_38 = { error: e_38_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_38) throw e_38.error; }
            }
        }
        return data;
    };
    GenerateOfferResultDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new GenerateOfferResultDto();
        result.init(json);
        return result;
    };
    return GenerateOfferResultDto;
}());
export { GenerateOfferResultDto };
var OfferFileUploadDto = /** @class */ (function () {
    function OfferFileUploadDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    OfferFileUploadDto.prototype.init = function (_data) {
        var e_39, _a;
        if (_data) {
            this.programId = _data["programId"];
            this.fileUpload = _data["fileUpload"] ? FileUpload.fromJS(_data["fileUpload"]) : undefined;
            this.creatorUserId = _data["creatorUserId"];
            this.creationTime = _data["creationTime"] ? new Date(_data["creationTime"].toString()) : undefined;
            if (Array.isArray(_data["uploadedOfferIds"])) {
                this.uploadedOfferIds = [];
                try {
                    for (var _b = __values(_data["uploadedOfferIds"]), _c = _b.next(); !_c.done; _c = _b.next()) {
                        var item = _c.value;
                        this.uploadedOfferIds.push(item);
                    }
                }
                catch (e_39_1) { e_39 = { error: e_39_1 }; }
                finally {
                    try {
                        if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                    }
                    finally { if (e_39) throw e_39.error; }
                }
            }
            this.offersLoaded = _data["offersLoaded"];
            this.offersInvalid = _data["offersInvalid"];
            this.offersTotal = _data["offersTotal"];
            this.errorMessage = _data["errorMessage"];
        }
    };
    OfferFileUploadDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new OfferFileUploadDto();
        result.init(data);
        return result;
    };
    OfferFileUploadDto.prototype.toJSON = function (data) {
        var e_40, _a;
        data = typeof data === 'object' ? data : {};
        data["programId"] = this.programId;
        data["fileUpload"] = this.fileUpload ? this.fileUpload.toJSON() : undefined;
        data["creatorUserId"] = this.creatorUserId;
        data["creationTime"] = this.creationTime ? this.creationTime.toISOString() : undefined;
        if (Array.isArray(this.uploadedOfferIds)) {
            data["uploadedOfferIds"] = [];
            try {
                for (var _b = __values(this.uploadedOfferIds), _c = _b.next(); !_c.done; _c = _b.next()) {
                    var item = _c.value;
                    data["uploadedOfferIds"].push(item);
                }
            }
            catch (e_40_1) { e_40 = { error: e_40_1 }; }
            finally {
                try {
                    if (_c && !_c.done && (_a = _b.return)) _a.call(_b);
                }
                finally { if (e_40) throw e_40.error; }
            }
        }
        data["offersLoaded"] = this.offersLoaded;
        data["offersInvalid"] = this.offersInvalid;
        data["offersTotal"] = this.offersTotal;
        data["errorMessage"] = this.errorMessage;
        return data;
    };
    OfferFileUploadDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new OfferFileUploadDto();
        result.init(json);
        return result;
    };
    return OfferFileUploadDto;
}());
export { OfferFileUploadDto };
var FileUpload = /** @class */ (function () {
    function FileUpload(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    FileUpload.prototype.init = function (_data) {
        if (_data) {
            this.fileName = _data["fileName"];
            this.fileDescription = _data["fileDescription"];
            this.fileType = _data["fileType"];
            this.base64FileContent = _data["base64FileContent"];
            this.location = _data["location"];
            this.creationTime = _data["creationTime"] ? new Date(_data["creationTime"].toString()) : undefined;
            this.creatorUserId = _data["creatorUserId"];
            this.newFlag = _data["newFlag"];
            this.duplicateFileName = _data["duplicateFileName"];
        }
    };
    FileUpload.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new FileUpload();
        result.init(data);
        return result;
    };
    FileUpload.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["fileName"] = this.fileName;
        data["fileDescription"] = this.fileDescription;
        data["fileType"] = this.fileType;
        data["base64FileContent"] = this.base64FileContent;
        data["location"] = this.location;
        data["creationTime"] = this.creationTime ? this.creationTime.toISOString() : undefined;
        data["creatorUserId"] = this.creatorUserId;
        data["newFlag"] = this.newFlag;
        data["duplicateFileName"] = this.duplicateFileName;
        return data;
    };
    FileUpload.prototype.clone = function () {
        var json = this.toJSON();
        var result = new FileUpload();
        result.init(json);
        return result;
    };
    return FileUpload;
}());
export { FileUpload };
var AjaxResponseOfOfferFileUploadDto = /** @class */ (function () {
    function AjaxResponseOfOfferFileUploadDto(data) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
        }
    }
    AjaxResponseOfOfferFileUploadDto.prototype.init = function (_data) {
        if (_data) {
            this.result = _data["result"] ? OfferFileUploadDto.fromJS(_data["result"]) : undefined;
            this.targetUrl = _data["targetUrl"];
            this.success = _data["success"];
            this.error = _data["error"] ? ErrorInfo.fromJS(_data["error"]) : undefined;
            this.unAuthorizedRequest = _data["unAuthorizedRequest"];
            this.__abp = _data["__abp"];
        }
    };
    AjaxResponseOfOfferFileUploadDto.fromJS = function (data) {
        data = typeof data === 'object' ? data : {};
        var result = new AjaxResponseOfOfferFileUploadDto();
        result.init(data);
        return result;
    };
    AjaxResponseOfOfferFileUploadDto.prototype.toJSON = function (data) {
        data = typeof data === 'object' ? data : {};
        data["result"] = this.result ? this.result.toJSON() : undefined;
        data["targetUrl"] = this.targetUrl;
        data["success"] = this.success;
        data["error"] = this.error ? this.error.toJSON() : undefined;
        data["unAuthorizedRequest"] = this.unAuthorizedRequest;
        data["__abp"] = this.__abp;
        return data;
    };
    AjaxResponseOfOfferFileUploadDto.prototype.clone = function () {
        var json = this.toJSON();
        var result = new AjaxResponseOfOfferFileUploadDto();
        result.init(json);
        return result;
    };
    return AjaxResponseOfOfferFileUploadDto;
}());
export { AjaxResponseOfOfferFileUploadDto };
export var StepperLifeCycleStageDtoStatus;
(function (StepperLifeCycleStageDtoStatus) {
    StepperLifeCycleStageDtoStatus[StepperLifeCycleStageDtoStatus["_0"] = 0] = "_0";
    StepperLifeCycleStageDtoStatus[StepperLifeCycleStageDtoStatus["_1"] = 1] = "_1";
    StepperLifeCycleStageDtoStatus[StepperLifeCycleStageDtoStatus["_2"] = 2] = "_2";
    StepperLifeCycleStageDtoStatus[StepperLifeCycleStageDtoStatus["_3"] = 3] = "_3";
    StepperLifeCycleStageDtoStatus[StepperLifeCycleStageDtoStatus["_4"] = 4] = "_4";
})(StepperLifeCycleStageDtoStatus || (StepperLifeCycleStageDtoStatus = {}));
export var LocalizedValueLanguage;
(function (LocalizedValueLanguage) {
    LocalizedValueLanguage[LocalizedValueLanguage["_0"] = 0] = "_0";
    LocalizedValueLanguage[LocalizedValueLanguage["_1"] = 1] = "_1";
})(LocalizedValueLanguage || (LocalizedValueLanguage = {}));
export var GenerateOfferResultDtoResultCode;
(function (GenerateOfferResultDtoResultCode) {
    GenerateOfferResultDtoResultCode[GenerateOfferResultDtoResultCode["_0"] = 0] = "_0";
    GenerateOfferResultDtoResultCode[GenerateOfferResultDtoResultCode["_1"] = 1] = "_1";
    GenerateOfferResultDtoResultCode[GenerateOfferResultDtoResultCode["_2"] = 2] = "_2";
    GenerateOfferResultDtoResultCode[GenerateOfferResultDtoResultCode["_3"] = 3] = "_3";
    GenerateOfferResultDtoResultCode[GenerateOfferResultDtoResultCode["_4"] = 4] = "_4";
    GenerateOfferResultDtoResultCode[GenerateOfferResultDtoResultCode["_5"] = 5] = "_5";
    GenerateOfferResultDtoResultCode[GenerateOfferResultDtoResultCode["_6"] = 6] = "_6";
})(GenerateOfferResultDtoResultCode || (GenerateOfferResultDtoResultCode = {}));
var SwaggerException = /** @class */ (function (_super) {
    __extends(SwaggerException, _super);
    function SwaggerException(message, status, response, headers, result) {
        var _this = _super.call(this) || this;
        _this.isSwaggerException = true;
        _this.message = message;
        _this.status = status;
        _this.response = response;
        _this.headers = headers;
        _this.result = result;
        return _this;
    }
    SwaggerException.isSwaggerException = function (obj) {
        return obj.isSwaggerException === true;
    };
    return SwaggerException;
}(Error));
export { SwaggerException };
function throwException(message, status, response, headers, result) {
    if (result !== null && result !== undefined)
        return Observable.throw(result);
    else
        return Observable.throw(new SwaggerException(message, status, response, headers, null));
}
function blobToText(blob) {
    return new Observable(function (observer) {
        if (!blob) {
            observer.next("");
            observer.complete();
        }
        else {
            var reader = new FileReader();
            reader.onload = function (event) {
                observer.next(event.target.result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}
//# sourceMappingURL=om-offer.js.map